### PR TITLE
patched bug

### PR DESCRIPTION
**Pull request by Arif812**
visit_Compare couldnt analyze more than two comparators because the rhs was being analyzed on visit_boolop

### CODE REVIEW

**Comment by AsynchronousAI** [comment]
lgtm, could u try returning op_in and is to the node visitor directly?

**Comment by AsynchronousAI** [comment]
also why was generic visit removed it is a fallback for errors and good future proofing

**Comment by Arif812** [comment]
> also why was generic visit removed it is a fallback for errors and good future proofing

where did I remove that

**Comment by AsynchronousAI** [comment]
> > also why was generic visit removed it is a fallback for errors and good future proofing
> 
> where did I remove that

line 1383 nodevisitor

**Review by AsynchronousAI — APPROVED** [review]

**Pull request merged**
